"""initial schema baseline

Revision ID: 80790d0dc3c2
Revises: 
Create Date: 2026-06-14 12:19:11.933909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80790d0dc3c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backup_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('includes_db', sa.Boolean(), nullable=True),
    sa.Column('includes_uploads', sa.Boolean(), nullable=True),
    sa.Column('db_size_kb', sa.Float(), nullable=True),
    sa.Column('uploads_size_kb', sa.Float(), nullable=True),
    sa.Column('total_size_kb', sa.Float(), nullable=True),
    sa.Column('db_stats', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('emailed_to', sa.String(length=200), nullable=True),
    sa.Column('emailed_at', sa.DateTime(), nullable=True),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_records_backup_type'), 'backup_records', ['backup_type'], unique=False)
    op.create_index(op.f('ix_backup_records_created_at'), 'backup_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_backup_records_id'), 'backup_records', ['id'], unique=False)
    op.create_index(op.f('ix_backup_records_status'), 'backup_records', ['status'], unique=False)
    op.create_table('employee_custody_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_name', sa.String(length=200), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('total_given', sa.Float(), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=True),
    sa.Column('last_settlement_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_custody_balances_employee_name'), 'employee_custody_balances', ['employee_name'], unique=True)
    op.create_index(op.f('ix_employee_custody_balances_id'), 'employee_custody_balances', ['id'], unique=False)
    op.create_table('mf_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('monthly_fee', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='mfclientstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mf_clients_id'), 'mf_clients', ['id'], unique=False)
    op.create_index(op.f('ix_mf_clients_name'), 'mf_clients', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'ACCOUNTANT', 'VIEWER', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('specialization', sa.Text(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('record_name', sa.String(length=300), nullable=True),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('client_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PROSPECT', 'SUSPENDED', name='clientstatus'), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone2', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('governorate', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('commercial_register', sa.String(length=50), nullable=True),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('vat_number', sa.String(length=50), nullable=True),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('activity', sa.String(length=200), nullable=True),
    sa.Column('activity_code', sa.String(length=20), nullable=True),
    sa.Column('tax_type', sa.Enum('VAT', 'INCOME', 'WITHHOLDING', 'STAMP', 'NONE', name='taxtype'), nullable=True),
    sa.Column('monthly_fee', sa.Float(), nullable=True),
    sa.Column('contract_value', sa.Float(), nullable=True),
    sa.Column('payment_terms', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('tax_obligations', sa.JSON(), nullable=True),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('contract_renewal_date', sa.Date(), nullable=True),
    sa.Column('trade_name', sa.String(length=200), nullable=True),
    sa.Column('legal_entity', sa.String(length=100), nullable=True),
    sa.Column('company_status', sa.String(length=30), nullable=True),
    sa.Column('activity_start_date', sa.Date(), nullable=True),
    sa.Column('activity_end_date', sa.Date(), nullable=True),
    sa.Column('preferred_lang', sa.String(length=5), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('assigned_accountant_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_accountant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_code'), 'clients', ['code'], unique=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_index(op.f('ix_clients_tax_number'), 'clients', ['tax_number'], unique=False)
    op.create_table('employee_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_name', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expense_items', sa.Text(), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=True),
    sa.Column('opening_balance', sa.Float(), nullable=True),
    sa.Column('custody_added', sa.Float(), nullable=True),
    sa.Column('closing_balance', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_settlements_date'), 'employee_settlements', ['date'], unique=False)
    op.create_index(op.f('ix_employee_settlements_employee_name'), 'employee_settlements', ['employee_name'], unique=False)
    op.create_index(op.f('ix_employee_settlements_id'), 'employee_settlements', ['id'], unique=False)
    op.create_index(op.f('ix_employee_settlements_month'), 'employee_settlements', ['month'], unique=False)
    op.create_index(op.f('ix_employee_settlements_year'), 'employee_settlements', ['year'], unique=False)
    op.create_table('mf_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('fee_amount', sa.Float(), nullable=True),
    sa.Column('balance_carried', sa.Float(), nullable=True),
    sa.Column('total_due', sa.Float(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('remaining', sa.Float(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('bayan', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['mf_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mf_records_client_id'), 'mf_records', ['client_id'], unique=False)
    op.create_index(op.f('ix_mf_records_id'), 'mf_records', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('payroll_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_gross', sa.Float(), nullable=True),
    sa.Column('total_deduct', sa.Float(), nullable=True),
    sa.Column('total_net', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_runs_id'), 'payroll_runs', ['id'], unique=False)
    op.create_table('quotation_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('legal_entity', sa.String(length=100), nullable=True),
    sa.Column('greeting', sa.String(length=100), nullable=True),
    sa.Column('deliverables', sa.JSON(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('default_expenses', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acc_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('account_subtype', sa.String(length=40), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=True),
    sa.Column('opening_balance', sa.Float(), nullable=True),
    sa.Column('opening_type', sa.String(length=10), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['acc_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acc_accounts_client_id'), 'acc_accounts', ['client_id'], unique=False)
    op.create_index(op.f('ix_acc_accounts_id'), 'acc_accounts', ['id'], unique=False)
    op.create_table('acc_journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('entry_number', sa.String(length=30), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('entry_type', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_debit', sa.Float(), nullable=True),
    sa.Column('total_credit', sa.Float(), nullable=True),
    sa.Column('is_balanced', sa.Boolean(), nullable=True),
    sa.Column('cost_center', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acc_journal_entries_client_id'), 'acc_journal_entries', ['client_id'], unique=False)
    op.create_index(op.f('ix_acc_journal_entries_entry_number'), 'acc_journal_entries', ['entry_number'], unique=False)
    op.create_index(op.f('ix_acc_journal_entries_id'), 'acc_journal_entries', ['id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('employee_name', sa.String(length=200), nullable=True),
    sa.Column('appt_date', sa.Date(), nullable=False),
    sa.Column('appt_time', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appt_date'), 'appointments', ['appt_date'], unique=False)
    op.create_index(op.f('ix_appointments_client_id'), 'appointments', ['client_id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_table('client_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_contacts_id'), 'client_contacts', ['id'], unique=False)
    op.create_table('client_portal_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('can_see_files', sa.Boolean(), nullable=True),
    sa.Column('can_see_invoices', sa.Boolean(), nullable=True),
    sa.Column('can_see_obligations', sa.Boolean(), nullable=True),
    sa.Column('can_see_reports', sa.Boolean(), nullable=True),
    sa.Column('can_see_tasks', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index(op.f('ix_client_portal_users_id'), 'client_portal_users', ['id'], unique=False)
    op.create_index(op.f('ix_client_portal_users_username'), 'client_portal_users', ['username'], unique=True)
    op.create_table('client_required_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('doc_name', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_received', sa.Boolean(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_required_docs_client_id'), 'client_required_docs', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_required_docs_id'), 'client_required_docs', ['id'], unique=False)
    op.create_table('collection_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_name_free', sa.String(length=200), nullable=True),
    sa.Column('collection_type', sa.Enum('ESTABLISHMENT', 'MONTHLY_FEE', name='collectiontype'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('agreed_amount', sa.Float(), nullable=False),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('monthly_amount', sa.Float(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurring_day', sa.Integer(), nullable=True),
    sa.Column('total_paid', sa.Float(), nullable=True),
    sa.Column('total_remaining', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('UNPAID', 'PARTIAL', 'PAID', 'OVERDUE', name='paymentstatus'), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_contracts_id'), 'collection_contracts', ['id'], unique=False)
    op.create_table('company_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('doc_name', sa.String(length=200), nullable=True),
    sa.Column('doc_number', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('alert_days', sa.String(length=50), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_documents_id'), 'company_documents', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('original_name', sa.String(length=300), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('gdrive_file_id', sa.String(length=100), nullable=True),
    sa.Column('gdrive_view_url', sa.String(length=500), nullable=True),
    sa.Column('gdrive_thumb_url', sa.String(length=500), nullable=True),
    sa.Column('gdrive_mime_type', sa.String(length=100), nullable=True),
    sa.Column('gdrive_folder_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('eta_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('eta_client_id', sa.String(length=300), nullable=False),
    sa.Column('eta_client_secret', sa.Text(), nullable=False),
    sa.Column('company_tin', sa.String(length=50), nullable=True),
    sa.Column('company_name_eta', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=50), nullable=True),
    sa.Column('last_sync_message', sa.Text(), nullable=True),
    sa.Column('total_docs_synced', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eta_credentials_client_id'), 'eta_credentials', ['client_id'], unique=True)
    op.create_index(op.f('ix_eta_credentials_id'), 'eta_credentials', ['id'], unique=False)
    op.create_table('financial_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('statement_type', sa.String(length=50), nullable=True),
    sa.Column('is_printed', sa.Boolean(), nullable=True),
    sa.Column('printed_at', sa.DateTime(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_signed', sa.Boolean(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_statements_id'), 'financial_statements', ['id'], unique=False)
    op.create_table('fixed_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('asset_number', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_value', sa.Float(), nullable=False),
    sa.Column('useful_life_years', sa.Float(), nullable=True),
    sa.Column('residual_value', sa.Float(), nullable=True),
    sa.Column('depreciation_method', sa.String(length=30), nullable=True),
    sa.Column('annual_depreciation', sa.Float(), nullable=True),
    sa.Column('accumulated_dep', sa.Float(), nullable=True),
    sa.Column('book_value', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('disposal_date', sa.Date(), nullable=True),
    sa.Column('disposal_value', sa.Float(), nullable=True),
    sa.Column('disposal_reason', sa.Text(), nullable=True),
    sa.Column('last_dep_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixed_assets_asset_number'), 'fixed_assets', ['asset_number'], unique=False)
    op.create_index(op.f('ix_fixed_assets_client_id'), 'fixed_assets', ['client_id'], unique=False)
    op.create_index(op.f('ix_fixed_assets_id'), 'fixed_assets', ['id'], unique=False)
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_id'), 'folders', ['id'], unique=False)
    op.create_table('government_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('paper_type', sa.String(length=100), nullable=False),
    sa.Column('paper_number', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('has_copy', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_papers_client_id'), 'government_papers', ['client_id'], unique=False)
    op.create_index(op.f('ix_government_papers_expiry_date'), 'government_papers', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_government_papers_id'), 'government_papers', ['id'], unique=False)
    op.create_table('hr_employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('national_id', sa.String(length=30), nullable=True),
    sa.Column('insurance_start_date', sa.Date(), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('base_salary', sa.Float(), nullable=True),
    sa.Column('variable_pay', sa.Float(), nullable=True),
    sa.Column('allowances', sa.Float(), nullable=True),
    sa.Column('insurance_number', sa.String(length=50), nullable=True),
    sa.Column('insurance_share', sa.Float(), nullable=True),
    sa.Column('company_insurance', sa.Float(), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_employees_id'), 'hr_employees', ['id'], unique=False)
    op.create_table('internal_mails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('from_person', sa.String(length=200), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('within_date', sa.DateTime(), nullable=True),
    sa.Column('closed_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_mails_id'), 'internal_mails', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.Enum('accounting', 'tax_returns', 'payroll', 'vat', 'audit', 'consultation', 'establishment', 'other', name='servicetype'), nullable=True),
    sa.Column('is_monthly_fee', sa.Boolean(), nullable=True),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('period_year', sa.Integer(), nullable=True),
    sa.Column('period_label', sa.String(length=50), nullable=True),
    sa.Column('included_obligations', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sent', 'paid', 'partial', 'overdue', 'cancelled', name='invoicestatus'), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('tax_percent', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('stamp_tax', sa.Float(), nullable=True),
    sa.Column('withholding_tax', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('remaining', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.Enum('cash', 'bank_transfer', 'check', 'instapay', 'vodafone_cash', name='paymentmethod'), nullable=True),
    sa.Column('bank_reference', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('governorate', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('service_requested', sa.String(), nullable=True),
    sa.Column('company_type', sa.String(), nullable=True),
    sa.Column('estimated_capital', sa.Float(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('has_office', sa.Boolean(), nullable=True),
    sa.Column('meeting_date', sa.DateTime(), nullable=True),
    sa.Column('company_activities', sa.Text(), nullable=True),
    sa.Column('suggested_name', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('lost_reason', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('has_existing_companies', sa.Boolean(), nullable=True),
    sa.Column('proposed_names', sa.Text(), nullable=True),
    sa.Column('quote_legal_entity', sa.String(), nullable=True),
    sa.Column('quote_activity', sa.String(), nullable=True),
    sa.Column('quote_location', sa.String(), nullable=True),
    sa.Column('quote_capital', sa.Float(), nullable=True),
    sa.Column('quote_total_fees', sa.Float(), nullable=True),
    sa.Column('quote_government_fees', sa.Float(), nullable=True),
    sa.Column('quote_expenses_total', sa.Float(), nullable=True),
    sa.Column('quote_services', sa.Text(), nullable=True),
    sa.Column('quote_required_docs', sa.Text(), nullable=True),
    sa.Column('quote_notes', sa.Text(), nullable=True),
    sa.Column('quote_deliver_docs', sa.Text(), nullable=True),
    sa.Column('converted_client_id', sa.Integer(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['converted_client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_code'), 'leads', ['code'], unique=True)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('office_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('fee_period', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_users', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_office_services_id'), 'office_services', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'waiting_docs', 'done', 'cancelled', name='taskstatus'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'), nullable=True),
    sa.Column('category', sa.Enum('TAX', 'ACCOUNTING', 'AUDIT', 'PAYROLL', 'LEGAL', 'CONSULTATION', 'OTHER', name='taskcategory'), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('actual_hours', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('task_date', sa.Date(), nullable=True),
    sa.Column('inline_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('tax_obligations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('obligation_type', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('auto_generated', sa.Boolean(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_obligations_id'), 'tax_obligations', ['id'], unique=False)
    op.create_table('tax_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('return_type', sa.Enum('VAT_MONTHLY', 'VAT_QUARTERLY', 'INCOME_ANNUAL', 'WITHHOLDING', 'STAMP_TAX', 'SALARY_TAX', name='taxreturntype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUBMITTED', 'APPROVED', 'REJECTED', 'LATE', name='taxreturnstatus'), nullable=True),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('period_quarter', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('penalty', sa.Float(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_returns_id'), 'tax_returns', ['id'], unique=False)
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=True),
    sa.Column('can_add', sa.Boolean(), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.Column('can_delete', sa.Boolean(), nullable=True),
    sa.Column('can_export', sa.Boolean(), nullable=True),
    sa.Column('can_approve', sa.Boolean(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module', 'client_id', name='uq_user_module_client')
    )
    op.create_index(op.f('ix_user_permissions_id'), 'user_permissions', ['id'], unique=False)
    op.create_table('acc_advances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('advance_type', sa.String(length=20), nullable=True),
    sa.Column('employee_name', sa.String(length=200), nullable=False),
    sa.Column('employee_id_ref', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('settled_amount', sa.Float(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['acc_journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acc_advances_client_id'), 'acc_advances', ['client_id'], unique=False)
    op.create_index(op.f('ix_acc_advances_id'), 'acc_advances', ['id'], unique=False)
    op.create_table('acc_journal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('account_code', sa.String(length=20), nullable=True),
    sa.Column('account_name', sa.String(length=200), nullable=True),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('partner_name', sa.String(length=200), nullable=True),
    sa.Column('cost_center', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['acc_accounts.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['acc_journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acc_journal_lines_id'), 'acc_journal_lines', ['id'], unique=False)
    op.create_table('acc_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('partner_name', sa.String(length=200), nullable=True),
    sa.Column('partner_tax_id', sa.String(length=50), nullable=True),
    sa.Column('doc_number', sa.String(length=30), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('vat_rate', sa.Float(), nullable=True),
    sa.Column('vat_amount', sa.Float(), nullable=True),
    sa.Column('withholding_rate', sa.Float(), nullable=True),
    sa.Column('withholding_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('net_amount', sa.Float(), nullable=True),
    sa.Column('expense_category', sa.String(length=100), nullable=True),
    sa.Column('cost_center', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['acc_journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acc_transactions_client_id'), 'acc_transactions', ['client_id'], unique=False)
    op.create_index(op.f('ix_acc_transactions_id'), 'acc_transactions', ['id'], unique=False)
    op.create_table('acc_treasuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('treasury_type', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('opening_balance', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['acc_accounts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acc_treasuries_client_id'), 'acc_treasuries', ['client_id'], unique=False)
    op.create_index(op.f('ix_acc_treasuries_id'), 'acc_treasuries', ['id'], unique=False)
    op.create_table('asset_depreciations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('book_value_after', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['fixed_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_depreciations_asset_id'), 'asset_depreciations', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_depreciations_id'), 'asset_depreciations', ['id'], unique=False)
    op.create_table('collection_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['collection_contracts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_expenses_id'), 'collection_expenses', ['id'], unique=False)
    op.create_table('collection_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('period_year', sa.Integer(), nullable=True),
    sa.Column('collected_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['collection_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_payments_id'), 'collection_payments', ['id'], unique=False)
    op.create_table('company_establishments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_name_en', sa.String(), nullable=True),
    sa.Column('company_type', sa.String(), nullable=True),
    sa.Column('activity', sa.String(), nullable=True),
    sa.Column('governorate', sa.String(), nullable=True),
    sa.Column('capital', sa.Float(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('name_reservation_status', sa.String(), nullable=True),
    sa.Column('name_reservation_date', sa.DateTime(), nullable=True),
    sa.Column('name_reservation_notes', sa.Text(), nullable=True),
    sa.Column('commercial_register_status', sa.String(), nullable=True),
    sa.Column('commercial_register_number', sa.String(), nullable=True),
    sa.Column('commercial_register_date', sa.DateTime(), nullable=True),
    sa.Column('commercial_register_notes', sa.Text(), nullable=True),
    sa.Column('tax_card_status', sa.String(), nullable=True),
    sa.Column('tax_card_number', sa.String(), nullable=True),
    sa.Column('tax_card_date', sa.DateTime(), nullable=True),
    sa.Column('tax_card_notes', sa.Text(), nullable=True),
    sa.Column('vat_registration_status', sa.String(), nullable=True),
    sa.Column('vat_number', sa.String(), nullable=True),
    sa.Column('vat_date', sa.DateTime(), nullable=True),
    sa.Column('vat_notes', sa.Text(), nullable=True),
    sa.Column('insurance_status', sa.String(), nullable=True),
    sa.Column('insurance_number', sa.String(), nullable=True),
    sa.Column('insurance_date', sa.DateTime(), nullable=True),
    sa.Column('insurance_notes', sa.Text(), nullable=True),
    sa.Column('bank_account_status', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_account_number', sa.String(), nullable=True),
    sa.Column('bank_date', sa.DateTime(), nullable=True),
    sa.Column('bank_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_establishments_code'), 'company_establishments', ['code'], unique=True)
    op.create_index(op.f('ix_company_establishments_id'), 'company_establishments', ['id'], unique=False)
    op.create_table('company_formation_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_name_en', sa.String(), nullable=True),
    sa.Column('company_type', sa.String(), nullable=True),
    sa.Column('activity', sa.String(), nullable=True),
    sa.Column('governorate', sa.String(), nullable=True),
    sa.Column('capital', sa.Float(), nullable=True),
    sa.Column('proposed_names', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('stage_entered_at', sa.DateTime(), nullable=True),
    sa.Column('agreed_fees', sa.Float(), nullable=True),
    sa.Column('government_fees', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('commercial_register_number', sa.String(), nullable=True),
    sa.Column('tax_card_number', sa.String(), nullable=True),
    sa.Column('vat_number', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_formation_cases_client_id'), 'company_formation_cases', ['client_id'], unique=False)
    op.create_index(op.f('ix_company_formation_cases_code'), 'company_formation_cases', ['code'], unique=True)
    op.create_index(op.f('ix_company_formation_cases_current_stage'), 'company_formation_cases', ['current_stage'], unique=False)
    op.create_index(op.f('ix_company_formation_cases_id'), 'company_formation_cases', ['id'], unique=False)
    op.create_table('file_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('original_name', sa.String(length=300), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_items_id'), 'file_items', ['id'], unique=False)
    op.create_table('follow_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('follow_up_type', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_ups_id'), 'follow_ups', ['id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('tax_percent', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.create_table('lead_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('metadata_', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_activities_id'), 'lead_activities', ['id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('meeting_link', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_table('monthly_dues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=50), nullable=True),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('amount_remaining', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('UNPAID', 'PARTIAL', 'PAID', 'OVERDUE', name='paymentstatus'), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['collection_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_dues_id'), 'monthly_dues', ['id'], unique=False)
    op.create_table('obligation_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obligation_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(), nullable=True),
    sa.Column('period_year', sa.Integer(), nullable=True),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('period_quarter', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('penalty', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['tax_obligations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligation_instances_id'), 'obligation_instances', ['id'], unique=False)
    op.create_table('office_service_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['office_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_office_service_tasks_id'), 'office_service_tasks', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'bank_transfer', 'check', 'instapay', 'vodafone_cash', name='paymentmethod'), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('payroll_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_name', sa.String(length=200), nullable=True),
    sa.Column('base_salary', sa.Float(), nullable=True),
    sa.Column('allowances', sa.Float(), nullable=True),
    sa.Column('overtime', sa.Float(), nullable=True),
    sa.Column('bonus', sa.Float(), nullable=True),
    sa.Column('gross_salary', sa.Float(), nullable=True),
    sa.Column('insurance_employee', sa.Float(), nullable=True),
    sa.Column('insurance_company', sa.Float(), nullable=True),
    sa.Column('income_tax', sa.Float(), nullable=True),
    sa.Column('deductions_other', sa.Float(), nullable=True),
    sa.Column('advances_deduct', sa.Float(), nullable=True),
    sa.Column('total_deductions', sa.Float(), nullable=True),
    sa.Column('net_salary', sa.Float(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['payroll_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_items_employee_id'), 'payroll_items', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_items_id'), 'payroll_items', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_items_run_id'), 'payroll_items', ['run_id'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_number', sa.String(length=30), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('client_phone', sa.String(length=30), nullable=True),
    sa.Column('client_email', sa.String(length=150), nullable=True),
    sa.Column('legal_entity', sa.String(length=100), nullable=True),
    sa.Column('activity', sa.String(length=300), nullable=True),
    sa.Column('activity_location', sa.String(length=100), nullable=True),
    sa.Column('capital', sa.Float(), nullable=True),
    sa.Column('deliverables', sa.JSON(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('extra_services', sa.JSON(), nullable=True),
    sa.Column('expenses_total', sa.Float(), nullable=True),
    sa.Column('government_fees', sa.Float(), nullable=True),
    sa.Column('office_fees', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('greeting', sa.String(length=100), nullable=True),
    sa.Column('advisor_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(), nullable=True),
    sa.Column('client_notes', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_id'), 'quotations', ['id'], unique=False)
    op.create_index(op.f('ix_quotations_quote_number'), 'quotations', ['quote_number'], unique=True)
    op.create_table('task_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_comments_id'), 'task_comments', ['id'], unique=False)
    op.create_table('time_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_entries_id'), 'time_entries', ['id'], unique=False)
    op.create_table('acc_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('check_type', sa.String(length=10), nullable=False),
    sa.Column('check_number', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('partner_name', sa.String(length=200), nullable=True),
    sa.Column('partner_phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('treasury_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['acc_journal_entries.id'], ),
    sa.ForeignKeyConstraint(['treasury_id'], ['acc_treasuries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acc_checks_client_id'), 'acc_checks', ['client_id'], unique=False)
    op.create_index(op.f('ix_acc_checks_id'), 'acc_checks', ['id'], unique=False)
    op.create_table('acc_treasury_txs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('treasury_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tx_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('to_treasury_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['acc_journal_entries.id'], ),
    sa.ForeignKeyConstraint(['to_treasury_id'], ['acc_treasuries.id'], ),
    sa.ForeignKeyConstraint(['treasury_id'], ['acc_treasuries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acc_treasury_txs_client_id'), 'acc_treasury_txs', ['client_id'], unique=False)
    op.create_index(op.f('ix_acc_treasury_txs_id'), 'acc_treasury_txs', ['id'], unique=False)
    op.create_index(op.f('ix_acc_treasury_txs_treasury_id'), 'acc_treasury_txs', ['treasury_id'], unique=False)
    op.create_table('eta_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('eta_uuid', sa.String(length=100), nullable=True),
    sa.Column('eta_long_id', sa.String(length=500), nullable=True),
    sa.Column('eta_hash_key', sa.String(length=500), nullable=True),
    sa.Column('internal_id', sa.String(length=100), nullable=True),
    sa.Column('doc_type', sa.String(length=5), nullable=True),
    sa.Column('doc_type_name', sa.String(length=50), nullable=True),
    sa.Column('doc_type_version', sa.String(length=10), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('issuer_tin', sa.String(length=50), nullable=True),
    sa.Column('issuer_name', sa.String(length=300), nullable=True),
    sa.Column('issuer_type', sa.String(length=20), nullable=True),
    sa.Column('receiver_tin', sa.String(length=50), nullable=True),
    sa.Column('receiver_name', sa.String(length=300), nullable=True),
    sa.Column('receiver_type', sa.String(length=20), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('issue_date_time', sa.DateTime(), nullable=True),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('period_year', sa.Integer(), nullable=True),
    sa.Column('total_sales_amount', sa.Float(), nullable=True),
    sa.Column('total_discount_amount', sa.Float(), nullable=True),
    sa.Column('net_amount', sa.Float(), nullable=True),
    sa.Column('total_tax_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('extra_discount_amount', sa.Float(), nullable=True),
    sa.Column('total_items_discount', sa.Float(), nullable=True),
    sa.Column('vat_amount', sa.Float(), nullable=True),
    sa.Column('table_discount_amount', sa.Float(), nullable=True),
    sa.Column('withholding_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('is_returned', sa.Boolean(), nullable=True),
    sa.Column('cancelled_by', sa.String(length=100), nullable=True),
    sa.Column('cancellation_date', sa.DateTime(), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('acc_tx_id', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acc_tx_id'], ['acc_transactions.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['acc_journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eta_documents_client_id'), 'eta_documents', ['client_id'], unique=False)
    op.create_index(op.f('ix_eta_documents_direction'), 'eta_documents', ['direction'], unique=False)
    op.create_index(op.f('ix_eta_documents_doc_date'), 'eta_documents', ['doc_date'], unique=False)
    op.create_index(op.f('ix_eta_documents_eta_uuid'), 'eta_documents', ['eta_uuid'], unique=True)
    op.create_index(op.f('ix_eta_documents_id'), 'eta_documents', ['id'], unique=False)
    op.create_index(op.f('ix_eta_documents_issuer_tin'), 'eta_documents', ['issuer_tin'], unique=False)
    op.create_index(op.f('ix_eta_documents_period_month'), 'eta_documents', ['period_month'], unique=False)
    op.create_index(op.f('ix_eta_documents_period_year'), 'eta_documents', ['period_year'], unique=False)
    op.create_index(op.f('ix_eta_documents_receiver_tin'), 'eta_documents', ['receiver_tin'], unique=False)
    op.create_index(op.f('ix_eta_documents_status'), 'eta_documents', ['status'], unique=False)
    op.create_table('formation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_stage', sa.String(), nullable=True),
    sa.Column('new_stage', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['company_formation_cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formation_events_case_id'), 'formation_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_formation_events_created_at'), 'formation_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_formation_events_id'), 'formation_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_formation_events_id'), table_name='formation_events')
    op.drop_index(op.f('ix_formation_events_created_at'), table_name='formation_events')
    op.drop_index(op.f('ix_formation_events_case_id'), table_name='formation_events')
    op.drop_table('formation_events')
    op.drop_index(op.f('ix_eta_documents_status'), table_name='eta_documents')
    op.drop_index(op.f('ix_eta_documents_receiver_tin'), table_name='eta_documents')
    op.drop_index(op.f('ix_eta_documents_period_year'), table_name='eta_documents')
    op.drop_index(op.f('ix_eta_documents_period_month'), table_name='eta_documents')
    op.drop_index(op.f('ix_eta_documents_issuer_tin'), table_name='eta_documents')
    op.drop_index(op.f('ix_eta_documents_id'), table_name='eta_documents')
    op.drop_index(op.f('ix_eta_documents_eta_uuid'), table_name='eta_documents')
    op.drop_index(op.f('ix_eta_documents_doc_date'), table_name='eta_documents')
    op.drop_index(op.f('ix_eta_documents_direction'), table_name='eta_documents')
    op.drop_index(op.f('ix_eta_documents_client_id'), table_name='eta_documents')
    op.drop_table('eta_documents')
    op.drop_index(op.f('ix_acc_treasury_txs_treasury_id'), table_name='acc_treasury_txs')
    op.drop_index(op.f('ix_acc_treasury_txs_id'), table_name='acc_treasury_txs')
    op.drop_index(op.f('ix_acc_treasury_txs_client_id'), table_name='acc_treasury_txs')
    op.drop_table('acc_treasury_txs')
    op.drop_index(op.f('ix_acc_checks_id'), table_name='acc_checks')
    op.drop_index(op.f('ix_acc_checks_client_id'), table_name='acc_checks')
    op.drop_table('acc_checks')
    op.drop_index(op.f('ix_time_entries_id'), table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_index(op.f('ix_task_comments_id'), table_name='task_comments')
    op.drop_table('task_comments')
    op.drop_index(op.f('ix_quotations_quote_number'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_payroll_items_run_id'), table_name='payroll_items')
    op.drop_index(op.f('ix_payroll_items_id'), table_name='payroll_items')
    op.drop_index(op.f('ix_payroll_items_employee_id'), table_name='payroll_items')
    op.drop_table('payroll_items')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_office_service_tasks_id'), table_name='office_service_tasks')
    op.drop_table('office_service_tasks')
    op.drop_index(op.f('ix_obligation_instances_id'), table_name='obligation_instances')
    op.drop_table('obligation_instances')
    op.drop_index(op.f('ix_monthly_dues_id'), table_name='monthly_dues')
    op.drop_table('monthly_dues')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_lead_activities_id'), table_name='lead_activities')
    op.drop_table('lead_activities')
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_follow_ups_id'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_file_items_id'), table_name='file_items')
    op.drop_table('file_items')
    op.drop_index(op.f('ix_company_formation_cases_id'), table_name='company_formation_cases')
    op.drop_index(op.f('ix_company_formation_cases_current_stage'), table_name='company_formation_cases')
    op.drop_index(op.f('ix_company_formation_cases_code'), table_name='company_formation_cases')
    op.drop_index(op.f('ix_company_formation_cases_client_id'), table_name='company_formation_cases')
    op.drop_table('company_formation_cases')
    op.drop_index(op.f('ix_company_establishments_id'), table_name='company_establishments')
    op.drop_index(op.f('ix_company_establishments_code'), table_name='company_establishments')
    op.drop_table('company_establishments')
    op.drop_index(op.f('ix_collection_payments_id'), table_name='collection_payments')
    op.drop_table('collection_payments')
    op.drop_index(op.f('ix_collection_expenses_id'), table_name='collection_expenses')
    op.drop_table('collection_expenses')
    op.drop_index(op.f('ix_asset_depreciations_id'), table_name='asset_depreciations')
    op.drop_index(op.f('ix_asset_depreciations_asset_id'), table_name='asset_depreciations')
    op.drop_table('asset_depreciations')
    op.drop_index(op.f('ix_acc_treasuries_id'), table_name='acc_treasuries')
    op.drop_index(op.f('ix_acc_treasuries_client_id'), table_name='acc_treasuries')
    op.drop_table('acc_treasuries')
    op.drop_index(op.f('ix_acc_transactions_id'), table_name='acc_transactions')
    op.drop_index(op.f('ix_acc_transactions_client_id'), table_name='acc_transactions')
    op.drop_table('acc_transactions')
    op.drop_index(op.f('ix_acc_journal_lines_id'), table_name='acc_journal_lines')
    op.drop_table('acc_journal_lines')
    op.drop_index(op.f('ix_acc_advances_id'), table_name='acc_advances')
    op.drop_index(op.f('ix_acc_advances_client_id'), table_name='acc_advances')
    op.drop_table('acc_advances')
    op.drop_index(op.f('ix_user_permissions_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_tax_returns_id'), table_name='tax_returns')
    op.drop_table('tax_returns')
    op.drop_index(op.f('ix_tax_obligations_id'), table_name='tax_obligations')
    op.drop_table('tax_obligations')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_office_services_id'), table_name='office_services')
    op.drop_table('office_services')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_code'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_internal_mails_id'), table_name='internal_mails')
    op.drop_table('internal_mails')
    op.drop_index(op.f('ix_hr_employees_id'), table_name='hr_employees')
    op.drop_table('hr_employees')
    op.drop_index(op.f('ix_government_papers_id'), table_name='government_papers')
    op.drop_index(op.f('ix_government_papers_expiry_date'), table_name='government_papers')
    op.drop_index(op.f('ix_government_papers_client_id'), table_name='government_papers')
    op.drop_table('government_papers')
    op.drop_index(op.f('ix_folders_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_index(op.f('ix_fixed_assets_id'), table_name='fixed_assets')
    op.drop_index(op.f('ix_fixed_assets_client_id'), table_name='fixed_assets')
    op.drop_index(op.f('ix_fixed_assets_asset_number'), table_name='fixed_assets')
    op.drop_table('fixed_assets')
    op.drop_index(op.f('ix_financial_statements_id'), table_name='financial_statements')
    op.drop_table('financial_statements')
    op.drop_index(op.f('ix_eta_credentials_id'), table_name='eta_credentials')
    op.drop_index(op.f('ix_eta_credentials_client_id'), table_name='eta_credentials')
    op.drop_table('eta_credentials')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_company_documents_id'), table_name='company_documents')
    op.drop_table('company_documents')
    op.drop_index(op.f('ix_collection_contracts_id'), table_name='collection_contracts')
    op.drop_table('collection_contracts')
    op.drop_index(op.f('ix_client_required_docs_id'), table_name='client_required_docs')
    op.drop_index(op.f('ix_client_required_docs_client_id'), table_name='client_required_docs')
    op.drop_table('client_required_docs')
    op.drop_index(op.f('ix_client_portal_users_username'), table_name='client_portal_users')
    op.drop_index(op.f('ix_client_portal_users_id'), table_name='client_portal_users')
    op.drop_table('client_portal_users')
    op.drop_index(op.f('ix_client_contacts_id'), table_name='client_contacts')
    op.drop_table('client_contacts')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_client_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appt_date'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_acc_journal_entries_id'), table_name='acc_journal_entries')
    op.drop_index(op.f('ix_acc_journal_entries_entry_number'), table_name='acc_journal_entries')
    op.drop_index(op.f('ix_acc_journal_entries_client_id'), table_name='acc_journal_entries')
    op.drop_table('acc_journal_entries')
    op.drop_index(op.f('ix_acc_accounts_id'), table_name='acc_accounts')
    op.drop_index(op.f('ix_acc_accounts_client_id'), table_name='acc_accounts')
    op.drop_table('acc_accounts')
    op.drop_table('quotation_templates')
    op.drop_index(op.f('ix_payroll_runs_id'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_mf_records_id'), table_name='mf_records')
    op.drop_index(op.f('ix_mf_records_client_id'), table_name='mf_records')
    op.drop_table('mf_records')
    op.drop_index(op.f('ix_employee_settlements_year'), table_name='employee_settlements')
    op.drop_index(op.f('ix_employee_settlements_month'), table_name='employee_settlements')
    op.drop_index(op.f('ix_employee_settlements_id'), table_name='employee_settlements')
    op.drop_index(op.f('ix_employee_settlements_employee_name'), table_name='employee_settlements')
    op.drop_index(op.f('ix_employee_settlements_date'), table_name='employee_settlements')
    op.drop_table('employee_settlements')
    op.drop_index(op.f('ix_clients_tax_number'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_code'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_mf_clients_name'), table_name='mf_clients')
    op.drop_index(op.f('ix_mf_clients_id'), table_name='mf_clients')
    op.drop_table('mf_clients')
    op.drop_index(op.f('ix_employee_custody_balances_id'), table_name='employee_custody_balances')
    op.drop_index(op.f('ix_employee_custody_balances_employee_name'), table_name='employee_custody_balances')
    op.drop_table('employee_custody_balances')
    op.drop_index(op.f('ix_backup_records_status'), table_name='backup_records')
    op.drop_index(op.f('ix_backup_records_id'), table_name='backup_records')
    op.drop_index(op.f('ix_backup_records_created_at'), table_name='backup_records')
    op.drop_index(op.f('ix_backup_records_backup_type'), table_name='backup_records')
    op.drop_table('backup_records')
    # ### end Alembic commands ###
